output-format: text

strictness: veryhigh
test-warnings: true
doc-warnings: false
member-warnings: true

uses:
  - django
  - celery

dodgy:
  run: false

pep8:
  full: true
  disable:
    - D100
    - D101
    - D102
    - D103
    - D105
    - D205
    - D400 
    - E701
    - N802
  options:
    max-line-length: 100

pyflakes:
  disable:
    - F999

pylint:
  disable:
    - unused-argument
    - too-few-public-methods
    - invalid-name
    - no-member
    - no-self-use 
    - anomalous-backslash-in-string
  options:
    max-line-length: 100

vulture:
  disable:
    - unused-function
    - unused-variable
    - unused-attribute
  run: true

ignore-paths:
  - node_modules
  - venv
  - env

ignore-patterns:
  - (^|/)migrations(/|$)
  - (^|/)settings(/|$)
