name: main
on: [push, pull_request]

jobs:
  build:
    name: Build {{project_name}}
    strategy:
      matrix:
        python: [3.11]
        node: [18.16]
    env:
      DATABASE_URL: 'sqlite:///'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Store branch and latest SHA
        run: |
          echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
        id: git
      - name: Setup Python ${% templatetag openvariable %} matrix.python {% templatetag closevariable %}
        uses: actions/setup-python@v2
        with:
          python-version: ${% templatetag openvariable %} matrix.python {% templatetag closevariable %}
      - name: Setup Node ${% templatetag openvariable %} matrix.node {% templatetag closevariable %}
        uses: actions/setup-node@v2
        with:
          node-version: ${% templatetag openvariable %} matrix.node {% templatetag closevariable %}
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache_name: node-modules-cache
        with:
          path: ~/.npm
          key: build-${% templatetag openvariable%} env.cache_name {% templatetag closevariable %}-${% templatetag openvariable%} steps.git.outputs.branch {% templatetag closevariable %}-${% templatetag openvariable%} steps.git.outputs.sha_short {% templatetag closevariable %}
          restore-keys: |
            build-${% templatetag openvariable%} env.cache_name {% templatetag closevariable %}-${% templatetag openvariable%} steps.git.outputs.branch {% templatetag closevariable %}-${% templatetag openvariable%} steps.git.outputs.sha_short {% templatetag closevariable %}
            build-${% templatetag openvariable%} env.cache_name {% templatetag closevariable %}-${% templatetag openvariable%} steps.git.outputs.branch {% templatetag closevariable %}
            build-${% templatetag openvariable%} env.cache_name {% templatetag closevariable %}
      - name: Cache pip
        uses: actions/cache@v2
        env:
          cache_name: pip-cache
        with:
          path: ~/.cache/pip
          key: build-${% templatetag openvariable%} env.cache_name {% templatetag closevariable %}-${% templatetag openvariable%} steps.git.outputs.branch {% templatetag closevariable %}-${% templatetag openvariable%} steps.git.outputs.sha_short {% templatetag closevariable %}
          restore-keys: |
            build-${% templatetag openvariable%} env.cache_name {% templatetag closevariable %}-${% templatetag openvariable%} steps.git.outputs.branch {% templatetag closevariable %}-${% templatetag openvariable%} steps.git.outputs.sha_short {% templatetag closevariable %}
            build-${% templatetag openvariable%} env.cache_name {% templatetag closevariable %}-${% templatetag openvariable%} steps.git.outputs.branch {% templatetag closevariable %}
            build-${% templatetag openvariable%} env.cache_name {% templatetag closevariable %}
      - run: python -m pip install --upgrade pip
      - run: python -m pip install poetry==1.5.1
      - run: curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash
      - run: sudo apt-get install git-lfs --upgrade
      - run: poetry install --with dev --no-root --no-interaction --no-ansi
      - run: npm install
      - run: npm run build
      - run: npm run lint
      - name: Generate secret key
        run: echo '::set-output name=SECRET_KEY::`python -c "import uuid; print(uuid.uuid4().hex + uuid.uuid4().hex)"`'
        id: secret_id_generator
      - name: Style check
        run: poetry run prospector --messages-only
        env:
          DJANGO_SETTINGS_MODULE: '{{project_name}}.settings.local_base'
          SECRET_KEY:  ${% templatetag openvariable %} steps.secret_id_generator.outputs.SECRET_KEY {% templatetag closevariable %}
          DATABASE_URL: 'sqlite:///'
          ALLOWED_HOSTS: '.example.org'
          SENDGRID_USERNAME: 'test'
          SENDGRID_PASSWORD: 'test'
          REDIS_URL: 'redis://'
      - name: Security checks
        run: poetry run bandit -c pyproject.toml -r backend
      - name: Imports check
        run: poetry run isort **/*.py --check-only
      - run: poetry run pre-commit run --all-files
        env:
          SKIP: prospector,isort,eslint,missing-migrations
      - run: poetry run python manage.py makemigrations --check --dry-run
        env:
          DJANGO_SETTINGS_MODULE: '{{project_name}}.settings.production'
          SECRET_KEY:  ${% templatetag openvariable %} steps.secret_id_generator.outputs.SECRET_KEY {% templatetag closevariable %}
          DATABASE_URL: 'sqlite:///'
          ALLOWED_HOSTS: '.example.org'
          SENDGRID_USERNAME: 'test'
          SENDGRID_PASSWORD: 'test'
          REDIS_URL: 'redis://'
        working-directory: backend
      - run: poetry run python manage.py check --deploy
        env:
          DJANGO_SETTINGS_MODULE: '{{project_name}}.settings.production'
          SECRET_KEY:  ${% templatetag openvariable %} steps.secret_id_generator.outputs.SECRET_KEY {% templatetag closevariable %}
          DATABASE_URL: 'sqlite:///'
          ALLOWED_HOSTS: '.example.org'
          SENDGRID_USERNAME: 'test'
          SENDGRID_PASSWORD: 'test'
          REDIS_URL: 'redis://'
        working-directory: backend
      - run: |
          poetry run coverage run manage.py test
          mkdir -p junit
          poetry run coverage xml -o junit/test-results.xml
        working-directory: backend
      - run: npm run test
