name: "Shared Build Steps"
description: "Shared build steps for main and nightly"

runs:
  using: "composite"
  steps:
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.8"
    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: "14.5"
    - run: python -m pip install --upgrade pip
      shell: bash
    - name: Install Django
      run: pip install "django>=3,<4"
      shell: bash
    - name: Setup testproject
      run: django-admin startproject testproject --extension py,yml,json,example --name Procfile,README.md --template=.
      shell: bash
    - run: |
        npm update --save
        npm update --save-dev
      shell: bash
      working-directory: testproject
    - run: npm install --no-optional
      working-directory: testproject
      shell: bash
    - run: npm dedupe
      working-directory: testproject
      shell: bash
    - run: npm run test
      working-directory: testproject
      shell: bash
    - run: npm run lint
      working-directory: testproject
      shell: bash
    - run: npm run build
      working-directory: testproject
      shell: bash
    - run: pip install requests pip-tools --upgrade
      working-directory: testproject
      shell: bash
    - run: |
        pip-compile requirements.in > requirements.txt
        pip-compile dev-requirements.in > dev-requirements.txt
      working-directory: testproject
      shell: bash
    - run: |
        pip install --user -r requirements.txt
        pip install --user -r dev-requirements.txt
      working-directory: testproject
      shell: bash
    - run: cp testproject/settings/local.py.example testproject/settings/local.py
      working-directory: testproject/backend
      shell: bash
    - run: cp .env.example .env
      working-directory: testproject/backend
      shell: bash
    - run: python manage.py makemigrations
      working-directory: testproject/backend
      env:
        DATABASE_URL: 'sqlite:///'
      shell: bash
    - run: python manage.py migrate
      working-directory: testproject/backend
      env:
        DATABASE_URL: 'sqlite:///'
      shell: bash
    - run: python manage.py test
      working-directory: testproject/backend
      env:
        DATABASE_URL: 'sqlite:///'
      shell: bash
    - name: Generate secret key
      run: echo '::set-output name=SECRET_KEY::`python -c "import uuid; print(uuid.uuid4().hex + uuid.uuid4().hex)"`'
      id: secret-id-generator
      shell: bash
    - run: prospector -X
      working-directory: testproject/backend
      env:
        SECRET_KEY: ${{ steps.secret-id-generator.outputs.SECRET_KEY }}
        SENDGRID_USERNAME: foo
        SENDGRID_PASSWORD: password
        DJANGO_SETTINGS_MODULE: 'testproject.settings.local'
        ALLOWED_HOSTS: '.example.org'
        REDIS_URL: 'redis://'
        DATABASE_URL: 'sqlite:///'
      shell: bash
    - run: python manage.py makemigrations --check --dry-run
      working-directory: testproject/backend
      env:
        DATABASE_URL: 'sqlite:///'
      shell: bash
    - run: python manage.py check --deploy --fail-level WARNING
      working-directory: testproject/backend
      env:
        SECRET_KEY: ${{ steps.secret-id-generator.outputs.SECRET_KEY }}
        SENDGRID_USERNAME: foo
        SENDGRID_PASSWORD: password
        DJANGO_SETTINGS_MODULE: 'testproject.settings.production'
        ALLOWED_HOSTS: '.example.org'
        REDIS_URL: 'redis://'
        DATABASE_URL: 'sqlite:///'
      shell: bash
